name: LiveRecorder
main: com.example.LiveRecorder
version: 1.0
api-version: 1.8
commands:
  live:
    description: 控制直播功能
    usage: /live <target|time|recorder|reset|reload> [args]
    permission: live.use
permissions:
  live.use:
    description: 允许使用直播指令
    default: true
