name: Build and Upload Artifact

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发构建
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
        
    # 设置 Java 环境（使用 Java 8）
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt' # 可选 'zulu', 'temurin', 'adopt' 等

    # 缓存 Gradle 依赖
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 构建项目
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean build

    # 上传生成的 JAR 文件为 Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LiveRecorder-JAR
        path: build/libs/LiveRecorder-*.jar
