name: Build and Deploy Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'  # Add this line specifying the JDK distribution

    - name: Build with Maven
      run: mvn clean install

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: LiveRecorder
        path: target/LiveRecorder-1.0.jar
